global using Xunit;
global using Moq;
global using Moq.Protected;
global using System.Net;
global using Newtonsoft.Json;
global using ProductViewer.Models;
global using ProductViewer.Services;
global using Microsoft.Extensions.Logging;
global using ProductViewer.Controllers;
global using IConfiguration = Microsoft.Extensions.Configuration.IConfiguration;
